import type { Metadata } from "next";
import "./globals.css";
import { connectToDB } from "./lib/mongodb";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connectToDB();
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
